src/lib/Bcfg2/Reporting/urls.py
from Bcfg2.Reporting.Compat import url, patterns  # django compat imports
from django.core.urlresolvers import reverse, NoReverseMatch
from django.http import HttpResponsePermanentRedirect
from Bcfg2.Reporting.utils import filteredUrls, paginatedUrls, timeviewUrls
from Bcfg2.Reporting import views

handler500 = 'Bcfg2.Reporting.views.server_error'

def newRoot(request):
    try:
        grid_view = reverse('reports_grid_view')
    except NoReverseMatch:
        grid_view = '/grid'
    return HttpResponsePermanentRedirect(grid_view)

urlpatterns = patterns('',
    (r'^$', newRoot),

    url(r'^manage/?$', views.client_manage, name='reports_client_manage'),
    url(r'^client/(?P<hostname>[^/]+)/(?P<pk>\d+)/?$', views.client_detail, name='reports_client_detail_pk'),
    url(r'^client/(?P<hostname>[^/]+)/?$', views.client_detail, name='reports_client_detail'),
    url(r'^element/(?P<entry_type>\w+)/(?P<pk>\d+)/(?P<interaction>\d+)?/?$', views.config_item, name='reports_item'),
    url(r'^element/(?P<entry_type>\w+)/(?P<pk>\d+)/?$', views.config_item, name='reports_item'),
    url(r'^entry/(?P<entry_type>\w+)/(?P<pk>\w+)/?$', views.entry_status, name='reports_entry'),
)

urlpatterns += patterns('',
    *timeviewUrls(
        (r'^summary/?$', views.display_summary, None, 'reports_summary'),
        (r'^timing/?$', views.display_timing, None, 'reports_timing'),
        (r'^common/group/(?P<group>[^/]+)/(?P<threshold>\d+)/?$', views.common_problems, None, 'reports_common_problems'),
        (r'^common/group/(?P<group>[^/]+)+/?$', views.common_problems, None, 'reports_common_problems'),
        (r'^common/(?P<threshold>\d+)/?$', views.common_problems, None, 'reports_common_problems'),
        (r'^common/?$', views.common_problems, None, 'reports_common_problems'),
))

urlpatterns += patterns('',
    *filteredUrls(*timeviewUrls(
        (r'^grid/?$', views.client_index, None, 'reports_grid_view'),
        (r'^detailed/?$',
            views.client_detailed_list, None, 'reports_detailed_list'),
        (r'^elements/(?P<item_state>\w+)/?$', views.config_item_list, None, 'reports_item_list'),
)))

urlpatterns += patterns('',
    *paginatedUrls( *filteredUrls(
        (r'^history/?$',
            views.render_history_view, None, 'reports_history'),
        (r'^history/(?P<hostname>[^/|]+)/?$',
            views.render_history_view, None, 'reports_client_history'),
)))

src/lib/Bcfg2/Reporting/models.py
"""Django models for Bcfg2 reports."""
import sys

import django
from django.core.exceptions import ImproperlyConfigured
try:
    from django.db import models, connections
except ImproperlyConfigured:
    e = sys.exc_info()[1]
    print("Reports: unable to import django models: %s" % e)
    sys.exit(1)

from django.core.cache import cache
from datetime import datetime, timedelta
from Bcfg2.Compat import cPickle
from Bcfg2.DBSettings import get_db_label


TYPE_GOOD = 0
TYPE_BAD = 1
TYPE_MODIFIED = 2
TYPE_EXTRA = 3

TYPE_CHOICES = (
    (TYPE_GOOD, 'Good'),
    (TYPE_BAD, 'Bad'),
    (TYPE_MODIFIED, 'Modified'),
    (TYPE_EXTRA, 'Extra'),
)

_our_backend = None


def convert_entry_type_to_id(type_name):
    """Convert a entry type to its entry id"""
    for e_id, e_name in TYPE_CHOICES:
        if e_name.lower() == type_name.lower():
            return e_id
    return -1


def hash_entry(entry_dict):
    """
    Build a key for this based on its data

    entry_dict = a dict of all the data identifying this
    """
    dataset = []
    for key in sorted(entry_dict.keys()):
        if key in ('id', 'hash_key') or key.startswith('_'):
            continue
        dataset.append((key, entry_dict[key]))
    return hash(cPickle.dumps(dataset))


def _quote(value):
    """
    Quote a string to use as a table name or column

    Newer versions and various drivers require an argument
    https://code.djangoproject.com/ticket/13630
    """
    global _our_backend
    if not _our_backend:
        if django.VERSION[0] == 1 and django.VERSION[1] >= 7:
            _our_backend = connections[get_db_label('Reporting')].ops
        else:
            from django.db import backend
            try:
                _our_backend = backend.DatabaseOperations(
                    connections[get_db_label('Reporting')])
            except TypeError:
                _our_backend = backend.DatabaseOperations()
    return _our_backend.quote_name(value)


class Client(models.Model):
    """Object representing every client we have seen stats for."""
    creation = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=128,)
    current_interaction = models.ForeignKey('Interaction',
                                            null=True, blank=True,
                                            related_name="parent_client")
    expiration = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name


class InteractionManager(models.Manager):
    """Manages interactions objects."""

    def recent_ids(self, maxdate=None):
        """
        Returns the ids of most recent interactions for clients as of a date.

        Arguments:
        maxdate -- datetime object.  Most recent date to pull. (default None)

        """
        from django.db import connections
        cursor = connections[get_db_label('Reporting')].cursor()
        cfilter = "expiration is null"

        sql = 'select ri.id, x.client_id from ' + \
              '(select client_id, MAX(timestamp) as timer from ' + \
              _quote('Reporting_interaction')
        if maxdate:
            if not isinstance(maxdate, datetime):
                raise ValueError('Expected a datetime object')
            sql = sql + " where timestamp <= '%s' " % maxdate
            cfilter = "(expiration is null or expiration > '%s') and creation <= '%s'" % (maxdate, maxdate)
        sql = sql + ' GROUP BY client_id) x, ' + \
                    _quote('Reporting_interaction') + \
                    ' ri where ri.client_id = x.client_id AND' + \
                    ' ri.timestamp = x.timer and x.client_id in' + \
                    ' (select id from %s where %s)' % \
                    (_quote('Reporting_client'), cfilter)
        try:
            cursor.execute(sql)
            return [item[0] for item in cursor.fetchall()]
        except:
            '''FIXME - really need some error handling'''
            pass
        return []

    def recent(self, maxdate=None):
        """
        Returns the most recent interactions for clients as of a date
        Arguments:
        maxdate -- datetime object.  Most recent date to pull. (dafault None)

        """
        if maxdate and not isinstance(maxdate, datetime):
            raise ValueError('Expected a datetime object')
        return self.filter(id__in=self.recent_ids(maxdate))


class Interaction(models.Model):
    """ Models each reconfiguration operation interaction between
    client and server. """
    client = models.ForeignKey(Client, related_name="interactions")
    timestamp = models.DateTimeField(db_index=True)  # Timestamp for this record
    state = models.CharField(max_length=32)  # good/bad/modified/etc
    repo_rev_code = models.CharField(max_length=64)  # repo revision at time of interaction
    server = models.CharField(max_length=256)  # server used for interaction
    good_count = models.IntegerField()  # of good config-items
    total_count = models.IntegerField()  # of total config-items
    bad_count = models.IntegerField(default=0)
    modified_count = models.IntegerField(default=0)
    extra_count = models.IntegerField(default=0)
    dry_run = models.BooleanField(default=False)
    only_important = models.BooleanField(default=False)

    actions = models.ManyToManyField("ActionEntry")
    packages = models.ManyToManyField("PackageEntry")
    paths = models.ManyToManyField("PathEntry")
    services = models.ManyToManyField("ServiceEntry")
    sebooleans = models.ManyToManyField("SEBooleanEntry")
    seports = models.ManyToManyField("SEPortEntry")
    sefcontexts = models.ManyToManyField("SEFcontextEntry")
    senodes = models.ManyToManyField("SENodeEntry")
    selogins = models.ManyToManyField("SELoginEntry")
    seusers = models.ManyToManyField("SEUserEntry")
    seinterfaces = models.ManyToManyField("SEInterfaceEntry")
    sepermissives = models.ManyToManyField("SEPermissiveEntry")
    semodules = models.ManyToManyField("SEModuleEntry")
    posixusers = models.ManyToManyField("POSIXUserEntry")
    posixgroups = models.ManyToManyField("POSIXGroupEntry")
    failures = models.ManyToManyField("FailureEntry")

    entry_types = ('actions', 'failures', 'packages',
                   'paths', 'services', 'sebooleans',
                   'seports', 'sefcontexts', 'senodes',
                   'selogins', 'seusers', 'seinterfaces',
                   'sepermissives', 'semodules', 'posixusers',
                   'posixgroups')

    # Formerly InteractionMetadata
    profile = models.ForeignKey("Group", related_name="+", null=True)
    groups = models.ManyToManyField("Group")
    bundles = models.ManyToManyField("Bundle")

    objects = InteractionManager()

    def __str__(self):
        return "With " + self.client.name + " @ " + self.timestamp.isoformat()

    def percentgood(self):
        if not self.total_count == 0:
            return (self.good_count / float(self.total_count)) * 100
        else:
            return 0

    def percentbad(self):
        if not self.total_count == 0:
            return ((self.total_count - self.good_count) /
                    (float(self.total_count))) * 100
        else:
            return 0

    def isclean(self):
        if (self.bad_count == 0 and self.good_count == self.total_count):
            return True
        else:
            return False

    def isstale(self):
        if (self == self.client.current_interaction):  # Is Mostrecent
            if(datetime.now() - self.timestamp > timedelta(hours=25)):
                return True
            else:
                return False
        else:
            #Search for subsequent Interaction for this client
            #Check if it happened more than 25 hrs ago.
            if (self.client.interactions.filter(timestamp__gt=self.timestamp)
                    .order_by('timestamp')[0].timestamp -
                    self.timestamp > timedelta(hours=25)):
                return True
            else:
                return False

    def save(self):
        super(Interaction, self).save()  # call the real save...
        self.client.current_interaction = self.client.interactions.latest()
        self.client.save()  # save again post update

    def delete(self):
        '''Override the default delete.  Allows us to remove
        Performance items '''
        pitems = list(self.performance_items.all())
        super(Interaction, self).delete()
        for perf in pitems:
            if perf.interaction.count() == 0:
                perf.delete()

    def badcount(self):
        return self.total_count - self.good_count

    def bad(self):
        rv = []
        for entry in self.entry_types:
            if entry == 'failures':
                continue
            rv.extend(getattr(self, entry).filter(state=TYPE_BAD))
        return rv

    def modified(self):
        rv = []
        for entry in self.entry_types:
            if entry == 'failures':
                continue
            rv.extend(getattr(self, entry).filter(state=TYPE_MODIFIED))
        return rv

    def extra(self):
        rv = []
        for entry in self.entry_types:
            if entry == 'failures':
                continue
            rv.extend(getattr(self, entry).filter(state=TYPE_EXTRA))
        return rv

    class Meta:
        get_latest_by = 'timestamp'
        ordering = ['-timestamp']
        unique_together = ("client", "timestamp")


class Performance(models.Model):
    """Object representing performance data for any interaction."""
    interaction = models.ForeignKey(Interaction,
                                    related_name="performance_items")
    metric = models.CharField(max_length=128)
    value = models.DecimalField(max_digits=32, decimal_places=16)

    def __str__(self):
        return self.metric


class Group(models.Model):
    """
    Groups extracted from interactions

    name - The group name

    TODO - Most of this is for future use
    TODO - set a default group

src/lib/Bcfg2/Reporting/templates/config_items/common.html
{% extends "base-timeview.html" %}
{% load bcfg2_tags %}
{% load url from bcfg2_compat %}

{% block title %}Bcfg2 - Common Problems{% endblock %}

{% block extra_header_info %}
{% endblock%}

{% block pagebanner %}Common configuration problems{% endblock %}

{% block content %}
  {% filter_navigator %}
  <div id='threshold_box'>
    <form method='post' action='{{ request.path }}'>
    <span>Showing items with more then {{ threshold }} entries</span>
    <input type='text' name='threshold' value='{{ threshold }}' maxlength='5' size='5' />
    <input type='submit' value='Change' />
    </form>
  </div>
  {% for type_name, type_list in lists %}
    <div class='entry_list'>
      <div class='entry_list_head element_list_head' onclick='javascript:toggleMe("table_{{ type_name }}");'>
        <h3>{{ type_name|capfirst }} entries</h3>
        <div class='entry_expand_tab' id='plusminus_table_{{ type_name }}'>[&ndash;]</div>
      </div>
    {% if type_list %}
      <table id='table_{{ type_name }}' class='entry_list'>
      <tr style='text-align: left'><th>Type</th><th>Name</th><th>Count</th><th>Reason</th></tr>
      {% for item in type_list %}
        <tr class='{% cycle listview,listview_alt %}'>
          <td>{{ item.ENTRY_TYPE }}</td>
          <td><a href='{% url "reports_entry" item.class_name  item.pk %}'>{{ item.name }}</a></td>
          <td>{{ item.num_entries }}</td>
          <td><a href='{% url "reports_item" item.ENTRY_TYPE  item.pk %}'>{{ item.short_list|join:"," }}</a></td>
        </tr>
      {% endfor %}
      </table>
    {% else %}
    <p>There are currently no inconsistent {{ type_name }} configuration entries.</p>
    {% endif %}
    </div>
  {% endfor %}
{% endblock %}

src/lib/Bcfg2/Reporting/templates/config_items/entry_status.html
{% extends "base-timeview.html" %}
{% load bcfg2_tags %}
{% load url from bcfg2_compat %}

{% block title %}Bcfg2 - Entry Status{% endblock %}

{% block extra_header_info %}
{% endblock%}

{% block pagebanner %}{{ entry.entry_type }} entry {{ entry.name }} status{% endblock %}

{% block content %}
{% filter_navigator %}
{% if items %}
    <div class='entry_list'>
      <table class='entry_list'>
          <tr style='text-align: left' ><th>Name</th><th>Timestamp</th><th>State</th><th>Reason</th></tr>
        {% for item, inters in items %}
          {% for inter in inters %}
          <tr class='{% cycle listview,listview_alt %}'>
            <td><a href='{% url "reports_client_detail" hostname=inter.client.name %}'>{{inter.client.name}}</a></td>
            <td><a href='{% url "reports_client_detail_pk" hostname=inter.client.name pk=inter.pk %}' style="white-space: nowrap;">
              {{inter.timestamp|date:"SHORT_DATETIME_FORMAT"|safe}}
            </a></td>
            <td>{{ item.get_state_display }}</td>
            <td style='white-space: nowrap'><a href='{% url "reports_item" entry_type=item.class_name pk=item.pk %}'>({{item.pk}}) {{item.short_list|join:","}}</a></td>
          </tr>
          {% endfor %}
        {% endfor %}
      </table>
    </div>
{% else %}
    <p>There are currently no hosts with this configuration entry.</p>
{% endif %}
{% endblock %}

src/lib/Bcfg2/Reporting/templates/config_items/item-failure.html
{% extends "config_items/item.html" %}
{% load syntax_coloring %}

{% block item_details %}
<div class='entry_list'>
    <div class='entry_list_head'>
        <h3>This item failed to bind on the server</h3>
    </div>
    <div class='diff_wrapper'>
        {{ item.message|syntaxhilight:"py" }}
    </div>
</div>
{% endblock %}

src/lib/Bcfg2/Reporting/templates/config_items/item.html
{% extends "base.html" %}
{% load split %}
{% load syntax_coloring %}
{% load url from bcfg2_compat %}

{% block title %}Bcfg2 - Element Details{% endblock %}


{% block extra_header_info %}
<style type="text/css">
#table_list_header {
    font-size: 100%;
}
table.entry_list {
    width: auto;
}
div.information_wrapper {
    margin: 15px;
}
div.diff_wrapper {
    overflow: auto;
}
div.entry_list h3 {
    font-size: 90%;
    padding: 5px;
}
</style>
{% endblock%}

{% block pagebanner %}Element Details{% endblock %}

{% block content %}
    <div class='detail_header'>
      <h3>{{item.get_state_display}} {{item.entry_type}}: {{item.name}}</h3>
    </div>

  <div class="information_wrapper">
{% block item_details %}
  {% if item.is_extra %}
  <p>This item exists on the host but is not defined in the configuration.</p>
  {% endif %}

  {% if not item.exists %}
  <div class="warning">This item does not currently exist on the host but is specified to exist in the configuration.</div>
  {% endif %}

{# Really need a better test here #}
{% if item.mode_problem or item.status_problem or item.linkentry.link_problem or item.version_problem %}
  <table class='entry_list'>
      <tr id='table_list_header'>
          <td style='text-align: right;'>Problem Type</td><td>Expected</td><td style='border-bottom: 1px solid #98DBCC;'>Found</td></tr>
  {% if item.mode_problem %}
      {% if item.current_perms.owner %}
      <tr><td style='text-align: right'><b>Owner</b></td>
          <td>{{item.target_perms.owner}}</td>
          <td>{{item.current_perms.owner}}</td></tr>
      {% endif %}
      {% if item.current_perms.group %}
      <tr><td style='text-align: right'><b>Group</b></td>
          <td>{{item.target_perms.group}}</td>
          <td>{{item.current_perms.group}}</td></tr>
      {% endif %}
      {% if item.current_perms.mode%}
      <tr><td style='text-align: right'><b>Permissions</b>
          </td><td>{{item.target_perms.mode}}</td>
          <td>{{item.current_perms.mode}}</td></tr>
      {% endif %}
  {% endif %}
  {% if item.status_problem %}
  <tr><td style='text-align: right'><b>Status</b></td>
      <td>{{item.target_status}}</td>
      <td>{{item.current_status}}</td></tr>
  {% endif %}
  {% if item.linkentry.link_problem %}
  <tr><td style='text-align: right'><b>{{item.get_path_type_display}}</b></td>
      <td>{{item.linkentry.target_path}}</td>
      <td>{{item.linkentry.current_path}}</td></tr>
  {% endif %}
  {% if item.version_problem %}
    <tr><td style='text-align: right'><b>Package Version</b></td>
        <td>{{item.target_version|cut:"("|cut:")"}}</td>
        <td>{{item.current_version|cut:"("|cut:")"}}</td></tr>
  {% endif %}
  {% if item.selinuxtype_problem %}
    <tr><td style='text-align: right'><b>SELinux Type</b></td>
        <td>{{item.selinuxtype}}</td>
        <td>{{item.current_selinuxtype}}</td></tr>
  {% endif %}
  </table>
{% endif %}

  {% if item.has_detail %}
    <div class='entry_list'>
      <div class='entry_list_head'>
        {% if item.is_sensitive %}
          <h3>File contents unavailable, as they might contain sensitive data.</h3>
        {% else %}
          <h3>Incorrect file contents ({{item.get_detail_type_display}})</h3>
        {% endif %}
      </div>
      {% if item.is_diff %}
        <div class='diff_wrapper'>
          {{ item.details|syntaxhilight }}
        </div>
      {% else %}
        {{ item.details|linebreaks }}
      {% endif %}
    </div>
  {% endif %}

  <!-- display extra directory entries -->
  {% if item.reason.unpruned %}
    <div class='entry_list'>
      <div class='entry_list_head'>
          <h3>Extra entries found</h3>
      </div>
      <table class='entry_list' cellpadding='3'>
        {% for unpruned_item in item.reason.unpruned|split %}
          <tr><td>{{ unpruned_item }}</td></tr>
        {% endfor %}
      </table>
    </div>
  {% endif %}
{% endblock %}


  <div class='entry_list'>
    <div class='entry_list_head'>
      <h3>Occurences on {{ timestamp|date:"SHORT_DATE_FORMAT" }}</h3>
    </div>
    {% if associated_list %}
      <table class="entry_list" cellpadding="3">
        {% for inter in associated_list %}
          <tr><td><a href='{% url "reports_client_detail" inter.client.name %}'
              >{{inter.client.name}}</a></td>
          <td><a href='{% url "reports_client_detail_pk" hostname=inter.client.name pk=inter.id %}'
              >{{inter.timestamp}}</a></td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
      <p>Missing client list</p>
    {% endif %}
  </div>

  </div><!-- information_wrapper -->
{% endblock %}

src/lib/Bcfg2/Reporting/templates/config_items/listing.html
{% extends "base-timeview.html" %}
{% load bcfg2_tags %}
{% load url from bcfg2_compat %}

{% block title %}Bcfg2 - Element Listing{% endblock %}

{% block extra_header_info %}
{% endblock%}

{% block pagebanner %}{{item_state|capfirst}} Element Listing{% endblock %}

{% block content %}
{% filter_navigator %}
{% if item_list %}
  {% for type_name, type_data in item_list %}
    <div class='entry_list'>
      <div class='entry_list_head element_list_head' onclick='javascript:toggleMe("table_{{ type_name }}");'>
        <h3>{{ type_name }} &#8212; {{ type_data|length }}</h3>
        <div class='entry_expand_tab' id='plusminus_table_{{ type_name }}'>[&ndash;]</div>
  </div>
      <table id='table_{{ type_name }}' class='entry_list'>
        <tr style='text-align: left' ><th>Name</th><th>Count</th><th>Reason</th></tr>
        {% for entry in type_data %}
          <tr class='{% cycle listview,listview_alt %}'>
            <td><a href='{% url "reports_entry" entry.class_name entry.pk %}'>{{entry.name}}</a></td>
            <td>{{entry.num_entries}}</td>
            <td><a href='{% url "reports_item" entry.class_name entry.pk %}'>{{entry.short_list|join:","}}</a></td>
          </tr>
        {% endfor %}
      </table>
    </div>
  {% endfor %}
{% else %}
    <p>There are currently no inconsistent configuration entries.</p>
{% endif %}
{% endblock %}